### ISSUE TITLE
Button overflow on mobile devices

### ISSUE THREAD

**Issue by thisislawatts** [techworkersco/twc-site-nl#9]
## Current behaviour

The long button text pushes out the header items, so that you only see _Menu_, a scroll action is required to read the full button text and see the Join call to action.

![CurrentBehaviour, demonstrates a button with text overflowing the viewport](https://github.com/techworkersco/twc-site-nl/assets/472589/c8020b81-2642-4c3f-9d8a-63932a8dbc9d)

I explored 2 possible solutions:
1. Update CSS styling for buttons to more gracefully wrap long text across multiple lines.
2. Rewrite copy to move long text out of button into paragraph before hand, also introduced Heading style for _Your voice matters._ text to create additional visual hierarchy to mark out that section. 

Updated CSS styling to wrap text over multiple lines.
![Screenshot 2024-06-14 at 15 37 40](https://github.com/techworkersco/twc-site-nl/assets/472589/25462a44-0e6c-4261-8812-404126160042)

Updated copy to make button text shorter. 
![Screenshot 2024-06-14 at 15 53 08](https://github.com/techworkersco/twc-site-nl/assets/472589/d92dfd0a-9242-4edb-abda-6c31f8a069cd)

**Comment by thisislawatts** [comment]
Any preferences on which path to take?

**Comment by dometto** [comment]
Visually I personally think the second option looks better! And maybe the more general "share your thoughts" message is actually also not be a bad idea?

**Comment by b-n** [comment]
+1 to the second too

**Comment by thisislawatts** [comment]
Thanks both, I raised #10 implementing updated text.
